[game]
board_size = 20
num_moves = 30433
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/full.bin"

[network]
main_body_channels = 64
residual_blocks = 10
value_head_channels = 16
value_head_flat_layer_width = 64
policy_head_channels = 64
policy_convolution_kernel = 3

[training]
device = "mps"
num_epochs = 1
learning_rate = 1e-3
batch_size = 128
policy_loss_weight = 0.158
sampling_ratio = 2.0
window_size = 100000

[directories]
game_data_directory = "data/scrap/games/"
model_directory = "data/scrap/models"
training_directory = "data/scrap/training"
