num_concurrent_threads = 1024
duration_seconds = 10

[game]
board_size = 10
num_moves = 6233
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/half.bin"

[inference]
name = "default"
model_path = "static/networks/trivial_net_half.onnx"
batch_size = 128
executor = {
    type = "tensorrt",
    max_batch_size = 128,
    pool_size = 32
}